# Generated by Django 5.1 on 2025-01-31 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="file_path",
        ),
        migrations.AddField(
            model_name="file",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
